INSERT INTO categories (name, slug, description, sort_order) VALUES
('Breakfast',      'breakfast',       'Morning meals to start your day right',                        1),
('Lunch',          'lunch',           'Midday meals and light bites',                                 2),
('Dinner',         'dinner',          'Evening and main course meals',                                3),
('Appetizers',     'appetizers',      'Starters, small plates and finger foods',                      4),
('Desserts',       'desserts',        'Sweet endings, pastries and indulgent treats',                  5),
('Drinks',         'drinks',          'Juices, smoothies, cocktails, teas and more',                  6),
('Soups & Stews',  'soups-stews',     'Hearty broths, soups, stews and slow-cooked pots',             7),
('Salads',         'salads',          'Fresh salads, grain bowls and light plates',                   8),
('Rice & Grains',  'rice-grains',     'Rice dishes, pilafs, porridges and grain-based meals',         9),
('Pasta & Noodles','pasta-noodles',   'Pasta, noodles, dumplings and dough-based dishes',            10),
('Bread & Baking', 'bread-baking',    'Breads, pastries, cakes and everything baked',                11),
('Grilled & BBQ',  'grilled-bbq',     'Grilled meats, skewers, BBQ and smoked dishes',               12),
('Seafood',        'seafood',         'Fish, shrimp, shellfish and ocean-to-table recipes',           13),
('Vegetarian',     'vegetarian',      'Meat-free dishes packed with flavor',                         14),
('Vegan',          'vegan',           'Entirely plant-based recipes',                                15),
('Street Food',    'street-food',     'Snacks, wraps, sandwiches and on-the-go bites',               16),
('Sauces & Dips',  'sauces-dips',     'Dressings, marinades, dips, chutneys and condiments',         17),
('Healthy & Light','healthy-light',   'Low calorie, clean eating and nutritious meals',              18),
('Kid Friendly',   'kid-friendly',    'Simple, fun and family-approved recipes',                     19),
('Special Occasion','special-occasion','Celebration meals, holiday dishes and dinner party recipes', 20);
